// Copyright (C) 2024 Zac Sweers
// SPDX-License-Identifier: Apache-2.0
package dev.zacsweers.metro.compiler.ir.graph

import dev.drewhamilton.poko.Poko
import dev.zacsweers.metro.compiler.MetroAnnotations
import dev.zacsweers.metro.compiler.appendLineWithUnderlinedContent
import dev.zacsweers.metro.compiler.capitalizeUS
import dev.zacsweers.metro.compiler.expectAs
import dev.zacsweers.metro.compiler.graph.BaseBinding
import dev.zacsweers.metro.compiler.graph.LocationDiagnostic
import dev.zacsweers.metro.compiler.ir.BindsCallable
import dev.zacsweers.metro.compiler.ir.ClassFactory
import dev.zacsweers.metro.compiler.ir.Format
import dev.zacsweers.metro.compiler.ir.IrAnnotation
import dev.zacsweers.metro.compiler.ir.IrContextualTypeKey
import dev.zacsweers.metro.compiler.ir.IrMetroContext
import dev.zacsweers.metro.compiler.ir.IrTypeKey
import dev.zacsweers.metro.compiler.ir.ParentContext
import dev.zacsweers.metro.compiler.ir.ProviderFactory
import dev.zacsweers.metro.compiler.ir.allowEmpty
import dev.zacsweers.metro.compiler.ir.annotationClass
import dev.zacsweers.metro.compiler.ir.asContextualTypeKey
import dev.zacsweers.metro.compiler.ir.computeMultibindingId
import dev.zacsweers.metro.compiler.ir.createMapBindingId
import dev.zacsweers.metro.compiler.ir.implements
import dev.zacsweers.metro.compiler.ir.parameters.Parameter
import dev.zacsweers.metro.compiler.ir.parameters.Parameters
import dev.zacsweers.metro.compiler.ir.rawType
import dev.zacsweers.metro.compiler.ir.regularParameters
import dev.zacsweers.metro.compiler.ir.render
import dev.zacsweers.metro.compiler.ir.renderForDiagnostic
import dev.zacsweers.metro.compiler.ir.renderSourceLocation
import dev.zacsweers.metro.compiler.ir.requireSimpleType
import dev.zacsweers.metro.compiler.memoize
import dev.zacsweers.metro.compiler.reportCompilerBug
import dev.zacsweers.metro.compiler.symbols.Symbols
import java.util.TreeSet
import org.jetbrains.kotlin.ir.IrElement
import org.jetbrains.kotlin.ir.declarations.IrClass
import org.jetbrains.kotlin.ir.declarations.IrDeclarationContainer
import org.jetbrains.kotlin.ir.declarations.IrDeclarationWithName
import org.jetbrains.kotlin.ir.declarations.IrFunction
import org.jetbrains.kotlin.ir.declarations.IrPackageFragment
import org.jetbrains.kotlin.ir.declarations.IrProperty
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.declarations.IrValueParameter
import org.jetbrains.kotlin.ir.types.IrErrorType
import org.jetbrains.kotlin.ir.types.IrType
import org.jetbrains.kotlin.ir.types.typeOrFail
import org.jetbrains.kotlin.ir.util.callableId
import org.jetbrains.kotlin.ir.util.classId
import org.jetbrains.kotlin.ir.util.isPropertyAccessor
import org.jetbrains.kotlin.ir.util.parentClassOrNull
import org.jetbrains.kotlin.ir.util.parentDeclarationsWithSelf
import org.jetbrains.kotlin.ir.util.propertyIfAccessor
import org.jetbrains.kotlin.name.CallableId
import org.jetbrains.kotlin.name.ClassId

internal sealed interface IrBinding : BaseBinding<IrType, IrTypeKey, IrContextualTypeKey> {
  override val typeKey: IrTypeKey
    get() = contextualTypeKey.typeKey

  val scope: IrAnnotation?
  // Track the list of parameters, which may not have unique type keys
  val parameters: Parameters
  val nameHint: String
  override val contextualTypeKey: IrContextualTypeKey
  val reportableDeclaration: IrDeclarationWithName?

  /**
   * Returns true if this binding should be scoped (cached) in the graph. For most bindings, this is
   * true if [scope] != null.
   */
  fun isScoped(): Boolean = scope != null

  override fun renderLocationDiagnostic(
    short: Boolean,
    shortLocation: Boolean,
    underlineTypeKey: Boolean,
  ): LocationDiagnostic {
    // First check if we have the contributing file and line number
    val binding = this
    val locationString =
      reportableDeclaration?.renderSourceLocation(short = shortLocation)
        // Or the fully-qualified contributing class name
        // TODO is this right
        ?: parameters.allParameters.firstOrNull()?.typeKey?.render(short = short)
        // Or print the full set of info we know about the binding
        ?: buildString {
          appendLine("Unknown source location, this may be generated by the compiler.")
          appendLine("└─ Here's some additional information we have for the binding:")
          append("   ├─ Binding type: ")
          appendLine(binding.javaClass.simpleName)
          append("   └─ Binding information: ")
          appendLine(binding)
        }
    return LocationDiagnostic(
      locationString,
      renderDescriptionDiagnostic(short = short, underlineTypeKey = underlineTypeKey),
    )
  }

  sealed interface BindingWithAnnotations : IrBinding {
    val annotations: MetroAnnotations<IrAnnotation>
  }

  sealed interface InjectedClassBinding<T : InjectedClassBinding<T>> :
    BindingWithAnnotations, IrBinding {
    val type: IrClass

    fun withMapKey(mapKey: IrAnnotation?): T
  }

  @Poko
  class ConstructorInjected(
    @Poko.Skip override val type: IrClass,
    @Poko.Skip val classFactory: ClassFactory,
    override val annotations: MetroAnnotations<IrAnnotation>,
    override val typeKey: IrTypeKey,
    val injectedMembers: Set<IrContextualTypeKey>,
  ) : IrBinding, BindingWithAnnotations, InjectedClassBinding<ConstructorInjected> {
    override val parameters: Parameters = classFactory.targetFunctionParameters

    val isAssisted
      get() = classFactory.isAssistedInject

    override val dependencies: List<IrContextualTypeKey> by memoize {
      parameters.nonDispatchParameters.filterNot { it.isAssisted }.map { it.contextualTypeKey } +
        injectedMembers
    }

    override val scope: IrAnnotation?
      get() = annotations.scope

    override val nameHint: String = type.name.asString()
    override val contextualTypeKey: IrContextualTypeKey = IrContextualTypeKey.create(typeKey)

    override val reportableDeclaration: IrDeclarationWithName
      get() = type

    /**
     * Returns true this binding can be invoked directly without going through the factory. This is
     * used to optimize instance access by skipping factory creation.
     *
     * We can't use direct invocation if there are injected members because the factory handles
     * member injection
     */
    fun canBypassFactory(): Boolean = !classFactory.isAssistedInject && injectedMembers.isEmpty()

    fun parameterFor(typeKey: IrTypeKey) =
      classFactory.function.regularParameters.getOrNull(
        parameters.regularParameters.indexOfFirst { it.typeKey == typeKey }
      )

    override fun renderDescriptionDiagnostic(short: Boolean, underlineTypeKey: Boolean): String =
      buildString {
        type.renderForDiagnostic(
          short = short,
          annotations = annotations,
          underlineTypeKey = underlineTypeKey,
        )
      }

    override fun toString() = renderDescriptionDiagnostic(short = true, underlineTypeKey = false)

    override fun withMapKey(mapKey: IrAnnotation?): ConstructorInjected {
      if (mapKey == null) return this
      return ConstructorInjected(
        type = type,
        classFactory = classFactory,
        annotations = annotations.copy(mapKey = mapKey),
        typeKey = typeKey,
        injectedMembers = injectedMembers,
      )
    }
  }

  class ObjectClass(
    @Poko.Skip override val type: IrClass,
    override val annotations: MetroAnnotations<IrAnnotation>,
    override val typeKey: IrTypeKey,
  ) : IrBinding, BindingWithAnnotations, InjectedClassBinding<ObjectClass> {
    override val dependencies: List<IrContextualTypeKey> = emptyList()
    override val scope: IrAnnotation? = null
    override val parameters: Parameters = Parameters.empty()
    override val isImplicitlyDeferrable: Boolean = true

    override val nameHint: String = type.name.asString()
    override val contextualTypeKey: IrContextualTypeKey = IrContextualTypeKey.create(typeKey)

    override val reportableDeclaration: IrDeclarationWithName
      get() = type

    override fun renderDescriptionDiagnostic(short: Boolean, underlineTypeKey: Boolean): String =
      buildString {
        type.renderForDiagnostic(
          short = short,
          annotations = annotations,
          underlineTypeKey = underlineTypeKey,
        )
      }

    override fun toString() = renderDescriptionDiagnostic(short = true, underlineTypeKey = false)

    override fun withMapKey(mapKey: IrAnnotation?): ObjectClass {
      if (mapKey == null) return this
      return ObjectClass(type, annotations.copy(mapKey = mapKey), typeKey)
    }
  }

  /** A binding that is statically defined in a graph or binding container. */
  sealed interface StaticBinding : IrBinding, BindingWithAnnotations

  @Poko
  class Provided(
    @Poko.Skip val providerFactory: ProviderFactory,
    override val annotations: MetroAnnotations<IrAnnotation>,
    override val contextualTypeKey: IrContextualTypeKey,
    override val parameters: Parameters,
  ) : StaticBinding {

    init {
      if (contextualTypeKey.typeKey.type is IrErrorType) {
        error("wtf")
      }
    }

    override val dependencies: List<IrContextualTypeKey> by memoize {
      parameters.allParameters.map { it.contextualTypeKey }
    }

    override val scope: IrAnnotation?
      get() = annotations.scope

    val intoSet: Boolean
      get() = annotations.isIntoSet

    val elementsIntoSet: Boolean
      get() = annotations.isElementsIntoSet

    // TODO are both necessary? Is there any case where only one is specified?
    val intoMap: Boolean
      get() = annotations.isIntoMap

    val mapKey: IrAnnotation? = annotations.mapKey
    override val typeKey: IrTypeKey = contextualTypeKey.typeKey

    val isIntoMultibinding
      get() = annotations.isIntoMultibinding

    override val nameHint: String = providerFactory.callableId.callableName.asString()

    override val reportableDeclaration: IrDeclarationWithName
      get() = providerFactory.function

    fun parameterFor(typeKey: IrTypeKey): IrValueParameter {
      return parameters.allParameters
        .find { it.typeKey == typeKey }
        ?.ir
        ?.expectAs<IrValueParameter>()
        ?: reportCompilerBug(
          "No value parameter found for key $typeKey in ${providerFactory.callableId.asSingleFqName().asString()}."
        )
    }

    override fun renderDescriptionDiagnostic(short: Boolean, underlineTypeKey: Boolean) =
      buildString {
        renderForDiagnostic(
          declaration = providerFactory.function,
          short = short,
          typeKey = providerFactory.typeKey,
          annotations = providerFactory.annotations,
          parameters = providerFactory.parameters,
          isProperty = providerFactory.isPropertyAccessor,
          underlineTypeKey = underlineTypeKey,
        )
      }

    override fun toString() = renderDescriptionDiagnostic(short = true, underlineTypeKey = false)
  }

  /** Represents an aliased binding, i.e. `@Binds`. Can be a multibinding. */
  @Poko
  class Alias(
    override val typeKey: IrTypeKey,
    val aliasedType: IrTypeKey,
    val bindsCallable: BindsCallable?,
    override val parameters: Parameters,
  ) : StaticBinding {
    val ir = bindsCallable?.function
    override val annotations: MetroAnnotations<IrAnnotation> =
      bindsCallable?.callableMetadata?.annotations ?: MetroAnnotations.none()
    override val isAlias: Boolean = true

    init {
      if (ir != null && !annotations.isBinds) {
        reportCompilerBug("Aliases must be binds!")
      }
    }

    fun aliasedBinding(graph: IrBindingGraph): IrBinding {
      // O(1) lookup at this point
      return graph.requireBinding(aliasedType)
    }

    override val scope: IrAnnotation? = null
    override val dependencies: List<IrContextualTypeKey> =
      listOf(IrContextualTypeKey.create(aliasedType))
    override val nameHint: String = ir?.name?.asString() ?: typeKey.type.rawType().name.asString()
    override val contextualTypeKey: IrContextualTypeKey = IrContextualTypeKey(typeKey)

    override val reportableDeclaration: IrDeclarationWithName?
      get() = bindsCallable?.resolveSourceDeclaration()?.first

    override fun renderLocationDiagnostic(
      short: Boolean,
      shortLocation: Boolean,
      underlineTypeKey: Boolean,
    ): LocationDiagnostic {
      return if ((annotations.isIntoMultibinding || annotations.isBinds) && bindsCallable != null) {
        bindsCallable.renderLocationDiagnostic(short, parameters)
      } else {
        super.renderLocationDiagnostic(short, shortLocation, underlineTypeKey)
      }
    }

    override fun renderDescriptionDiagnostic(short: Boolean, underlineTypeKey: Boolean) =
      buildString {
        if (ir == null) {
          append("Synthetic alias of ")
          append(aliasedType.render(short = short, includeQualifier = true))
          append(" to ")
          append(typeKey.render(short = short, includeQualifier = true))
          return@buildString
        }
        renderForDiagnostic(
          declaration = ir,
          short = short,
          typeKey = typeKey,
          annotations = annotations,
          parameters = parameters,
          isProperty = null,
          underlineTypeKey = underlineTypeKey,
        )
      }

    override fun toString() = renderDescriptionDiagnostic(short = true, underlineTypeKey = false)
  }

  /**
   * Models an `@AssistedFactory` binding.
   *
   * The assisted factory encapsulates the assisted-inject target class. The target's
   * `ConstructorInjected` binding is stored directly here and does not participate in the main
   * binding graph. This design ensure the assisted-inject type cannot be considered for deferral
   * (its `MetroFactory` doesn't implement `Provider`)
   */
  @Poko
  class AssistedFactory(
    @Poko.Skip override val type: IrClass,
    @Poko.Skip val targetBinding: ConstructorInjected,
    @Poko.Skip val function: IrSimpleFunction,
    override val annotations: MetroAnnotations<IrAnnotation>,
    override val parameters: Parameters,
    override val typeKey: IrTypeKey,
    /**
     * Dependencies are the [targetBinding]'s non-assisted dependencies, wrapped in Provider. This
     * allows proper cycle detection at the Assisted binding level. Pre-computed at construction
     * time since wrapping requires [IrMetroContext].
     */
    override val dependencies: List<IrContextualTypeKey>,
  ) : IrBinding, BindingWithAnnotations, InjectedClassBinding<AssistedFactory> {
    override val nameHint: String = type.name.asString()
    override val scope: IrAnnotation? = null
    override val contextualTypeKey: IrContextualTypeKey = IrContextualTypeKey(typeKey)
    override val reportableDeclaration: IrDeclarationWithName
      get() = type

    override val isImplicitlyDeferrable: Boolean = true

    override fun withMapKey(mapKey: IrAnnotation?): AssistedFactory {
      if (mapKey == null) return this
      return AssistedFactory(
        type,
        targetBinding,
        function,
        annotations.copy(mapKey = mapKey),
        parameters,
        typeKey,
        dependencies,
      )
    }

    override fun renderDescriptionDiagnostic(short: Boolean, underlineTypeKey: Boolean) =
      buildString {
        append('(')
        append("@AssistedFactory")
        append(' ')
        type.parentClassOrNull?.let {
          append(it.name.asString())
          append('.')
        }
        append(typeKey.render(short = short, includeQualifier = false))
        append(')')
        append(' ')
        renderForDiagnostic(
          declaration = function,
          short = short,
          typeKey = typeKey,
          annotations = annotations,
          parameters = parameters,
          isProperty = null,
          underlineTypeKey = underlineTypeKey,
        )
      }

    override fun toString() = renderDescriptionDiagnostic(short = true, underlineTypeKey = false)
  }

  /**
   * Represents a bound instance in the graph.
   *
   * @property typeKey The type key of the bound instance
   * @property nameHint A hint for naming generated properties
   * @property reportableDeclaration The declaration to report in diagnostics
   * @property token Token for accessing a parent graph's property. When non-null, this binding
   *   accesses a property from an ancestor graph. When null, this is a self-binding where the graph
   *   provides itself (use `thisReceiver` in code gen).
   *     @property isGraphInput Indicates if this instance was passed as graph input (`@Provides`,
   *       `@Includes`, etc).
   */
  data class BoundInstance(
    override val typeKey: IrTypeKey,
    override val nameHint: String,
    override val reportableDeclaration: IrDeclarationWithName?,
    val irElement: IrElement? = null,
    val token: ParentContext.Token? = null,
    val isGraphInput: Boolean = false,
    override val contextualTypeKey: IrContextualTypeKey = IrContextualTypeKey(typeKey),
  ) : IrBinding {
    constructor(
      parameter: Parameter,
      reportableLocation: IrDeclarationWithName,
      isGraphInput: Boolean = false,
    ) : this(
      typeKey = parameter.typeKey,
      nameHint = "${parameter.name.asString()}Instance",
      reportableDeclaration = reportableLocation,
      isGraphInput = isGraphInput,
      contextualTypeKey = parameter.contextualTypeKey,
    )

    override val dependencies: List<IrContextualTypeKey> = emptyList()
    override val scope: IrAnnotation? = null
    override val parameters: Parameters = Parameters.empty()
    override val isImplicitlyDeferrable: Boolean = true

    override fun renderLocationDiagnostic(
      short: Boolean,
      shortLocation: Boolean,
      underlineTypeKey: Boolean,
    ): LocationDiagnostic {
      return super.renderLocationDiagnostic(short, shortLocation, underlineTypeKey)
    }

    override fun renderDescriptionDiagnostic(short: Boolean, underlineTypeKey: Boolean): String {
      return buildString {
        val renderedType = typeKey.render(short = short, includeQualifier = true)
        when {
          isGraphInput && reportableDeclaration is IrValueParameter -> {
            // Factory/creator parameter, e.g. "@Provides bar: Map<String, String>"
            val param = reportableDeclaration
            append("@Provides ")
            append(param.name.asString())
            append(": ")
            if (underlineTypeKey) {
              appendLineWithUnderlinedContent(renderedType)
            } else {
              append(renderedType)
            }
          }
          isGraphInput -> {
            // Binding container input
            if (underlineTypeKey) {
              appendLineWithUnderlinedContent(renderedType)
            } else {
              append(renderedType)
            }
            append(" (graph input)")
          }
          token != null -> {
            // Parent graph binding
            if (underlineTypeKey) {
              appendLineWithUnderlinedContent(renderedType)
            } else {
              append(renderedType)
            }
            append(" (bound from parent graph)")
          }
          else -> {
            // Graph self-binding
            if (underlineTypeKey) {
              appendLineWithUnderlinedContent(renderedType)
            } else {
              append(renderedType)
            }
            append(" (graph instance)")
          }
        }
      }
    }

    override fun toString() = renderDescriptionDiagnostic(short = true, underlineTypeKey = false)
  }

  data class Absent(override val typeKey: IrTypeKey) : IrBinding {
    override val dependencies: List<IrContextualTypeKey> = emptyList()
    override val scope: IrAnnotation? = null
    override val nameHint: String
      get() = reportCompilerBug("Should never be called")

    override val parameters: Parameters = Parameters.empty()
    override val contextualTypeKey: IrContextualTypeKey = IrContextualTypeKey(typeKey)
    override val isImplicitlyDeferrable: Boolean = true

    override val reportableDeclaration: IrDeclarationWithName? = null
    override val isTransient: Boolean = true

    override fun renderDescriptionDiagnostic(short: Boolean, underlineTypeKey: Boolean): String {
      return "Absent(${typeKey.render(short = short, includeQualifier = true)})"
    }

    override fun toString() = renderDescriptionDiagnostic(short = true, underlineTypeKey = false)
  }

  @Poko
  class GraphDependency(
    val ownerKey: IrTypeKey,
    @Poko.Skip val graph: IrClass,
    @Poko.Skip val getter: IrSimpleFunction? = null,
    override val typeKey: IrTypeKey,
    /**
     * Token for accessing a parent graph's property. This is set during validation and resolved to
     * an actual property during generation via the parent's [BindingPropertyContext].
     */
    @Poko.Skip val token: ParentContext.Token? = null,
    @Poko.Skip override val contextualTypeKey: IrContextualTypeKey = IrContextualTypeKey(typeKey),
  ) : IrBinding {
    // callableId is only used when getter is present (local graph dependency)
    // For parent property access (propertyAccessToken), the callableId is determined during
    // generation
    val callableId: CallableId?
      get() = getter?.callableId

    override val dependencies: List<IrContextualTypeKey> = listOf(IrContextualTypeKey(ownerKey))
    override val scope: IrAnnotation? = null
    override val nameHint: String = buildString {
      append(graph.name)
      if (token != null) {
        // Use the context key's type name as a hint
        append(token.contextKey.typeKey.type.rawType().name.asString().capitalizeUS())
      } else {
        val property = getter!!.correspondingPropertySymbol
        if (property != null) {
          val propName = property.owner.name.asString()
          append(propName.capitalizeUS())
        } else {
          append(getter.name.capitalizeUS())
        }
      }
    }
    override val parameters: Parameters = Parameters.empty()

    override val reportableDeclaration: IrDeclarationWithName?
      get() = getter?.propertyIfAccessor?.expectAs<IrDeclarationWithName>()

    override fun renderDescriptionDiagnostic(short: Boolean, underlineTypeKey: Boolean): String {
      return buildString {
        if (getter != null) {
          renderForDiagnostic(
            declaration = getter,
            short = short,
            typeKey = typeKey,
            annotations = MetroAnnotations.none(),
            parameters = Parameters.empty(),
            isProperty = null,
            underlineTypeKey = underlineTypeKey,
          )
        } else if (token != null) {
          // For parent property access via token, show the parent graph and type being accessed
          append(typeKey.render(short = short, includeQualifier = true))
          append(" (from ")
          append(ownerKey.render(short = short, includeQualifier = false))
          append(")")
        } else {
          // Fallback just in case
          append("GraphDependency(${typeKey.render(short = short, includeQualifier = true)})")
        }
      }
    }

    override fun toString() = renderDescriptionDiagnostic(short = true, underlineTypeKey = false)
  }

  // TODO sets
  //  unscoped always initializes inline? Dagger sometimes generates private getters
  @Poko
  class Multibinding(
    override val contextualTypeKey: IrContextualTypeKey,
    /** The original `@Multibinds` declaration, if any. Note this may point at a fake override. */
    @Poko.Skip var declaration: IrSimpleFunction?,
    val multibindsAnnotation: IrAnnotation?,
    val isSet: Boolean,
    val isMap: Boolean,
    /** Corresponds to @MultibindsElement.bindingId */
    val bindingId: String,
    var allowEmpty: Boolean,
    // Reconcile this with parametersByKey?
    // TreeSet sorting for consistency
    val sourceBindings: MutableSet<IrTypeKey> = TreeSet(),
  ) : IrBinding {
    override val typeKey: IrTypeKey = contextualTypeKey.typeKey
    override val scope: IrAnnotation? = null
    override val dependencies by memoize { sourceBindings.map { IrContextualTypeKey(it) } }
    override val parameters: Parameters = Parameters.empty()

    fun isEmpty() = sourceBindings.isEmpty()

    override val nameHint: String by memoize {
      buildString {
        if (isMap) {
          append("mapOf")
          val (k, v) = typeKey.type.requireSimpleType(declaration).arguments
          append(k.render(short = true).capitalizeUS())
          append("To")
          append(v.render(short = true).capitalizeUS())
        } else {
          append("setOf")
          append(
            typeKey.type
              .requireSimpleType(declaration)
              .arguments[0]
              .render(short = true)
              .capitalizeUS()
          )
        }
      }
    }

    override val reportableDeclaration: IrDeclarationWithName? = declaration

    override fun renderDescriptionDiagnostic(short: Boolean, underlineTypeKey: Boolean) =
      buildString {
        val decl = declaration
        if (decl != null) {
          renderForDiagnostic(
            declaration = decl,
            short = short,
            typeKey = typeKey,
            annotations = MetroAnnotations(multibinds = multibindsAnnotation),
            parameters = Parameters.empty(),
            isProperty = declaration?.isPropertyAccessor == true,
            underlineTypeKey = underlineTypeKey,
          )
        } else {
          typeKey.qualifier?.let {
            append(it.render(short = short))
            append(' ')
          }
          if (isSet) {
            append("Set<")
          } else {
            append("Map<")
          }
          append(typeKey.render(short = short, includeQualifier = false))
          append('>')
        }
      }

    fun addSourceBinding(source: IrTypeKey) {
      if (source in sourceBindings) {
        reportCompilerBug("Duplicate multibinding source: $source")
      }
      sourceBindings.add(source)
    }

    companion object {
      /**
       * Special case! Multibindings may be created under two conditions:
       * 1. Explicitly via `@Multibinds`
       * 2. Implicitly via a `@Provides` callable that contributes into a multibinding
       *
       * Because these may both happen, if the key already exists in the graph we won't try to add
       * it again
       */
      context(context: IrMetroContext)
      fun fromMultibindsDeclaration(
        getter: IrSimpleFunction,
        multibinds: IrAnnotation,
        contextualTypeKey: IrContextualTypeKey,
      ): Multibinding {
        return create(
          typeKey = contextualTypeKey.typeKey,
          declaration = getter,
          allowEmpty = multibinds.allowEmpty(),
          multibinds = multibinds,
        )
      }

      context(context: IrMetroContext)
      fun fromContributor(multibindingTypeKey: IrTypeKey): Multibinding {
        return create(
          typeKey = multibindingTypeKey,
          declaration = null,
          multibinds = null,
          allowEmpty = false,
        )
      }

      context(context: IrMetroContext)
      private fun create(
        typeKey: IrTypeKey,
        declaration: IrSimpleFunction?,
        multibinds: IrAnnotation?,
        allowEmpty: Boolean = false,
      ): Multibinding {
        val rawType = typeKey.type.rawType()

        val isSet = rawType.implements(context.irBuiltIns.setClass.owner.classId!!)
        val isMap = !isSet

        val bindingId: String =
          if (isMap) {
            val mapType = typeKey.type.requireSimpleType(declaration)
            val keyType = mapType.arguments[0].typeOrFail
            val valueType = mapType.arguments[1].typeOrFail
            val elementTypeKey = typeKey.copy(type = valueType)
            createMapBindingId(keyType, elementTypeKey)
          } else {
            typeKey.computeMultibindingId()
          }

        return Multibinding(
          contextualTypeKey =
            typeKey.type.asContextualTypeKey(
              qualifierAnnotation = typeKey.qualifier,
              hasDefault = false,
              patchMutableCollections = false,
              declaration = declaration,
            ),
          isSet = isSet,
          isMap = isMap,
          bindingId = bindingId,
          allowEmpty = allowEmpty,
          declaration = declaration,
          multibindsAnnotation = multibinds,
        )
      }
    }
  }

  data class MembersInjected(
    // Always MembersInjected<TargetClass>
    override val contextualTypeKey: IrContextualTypeKey,
    override val parameters: Parameters,
    override val reportableDeclaration: IrDeclarationWithName?,
    // Only present for inject() functions
    val function: IrFunction?,
    val isFromInjectorFunction: Boolean,
    val targetClassId: ClassId,
    /**
     * MembersInjector typekeys for supertypes that also have member injections. This ensures the
     * binding graph correctly tracks that injecting a subtype depends on injecting all its
     * supertypes' members.
     */
    val supertypeMembersInjectorKeys: List<IrContextualTypeKey> = emptyList(),
    /**
     * Dependencies inherited from supertype member injectors. Used by BindingPropertyCollector to
     * avoid double-counting when processing the hierarchy.
     */
    val supertypeDependencies: Set<IrContextualTypeKey> = emptySet(),
  ) : IrBinding {
    override val typeKey: IrTypeKey = contextualTypeKey.typeKey

    // MembersInjectors are always implicitly deferrable because they don't participate in
    // object instantiation
    override val isImplicitlyDeferrable: Boolean = true

    override val dependencies: List<IrContextualTypeKey> by memoize {
      // Note: supertypeMembersInjectorKeys are NOT included here because they're handled
      // specially by BindingPropertyCollector (only processed if they exist in the graph).
      parameters.nonDispatchParameters
        // Instance parameters are implicitly assisted in this scenario and marked as such in FIR
        .filterNot { it.isAssisted }
        .map { it.contextualTypeKey }
        .plus(supertypeMembersInjectorKeys)
    }

    override val scope: IrAnnotation? = null

    override val nameHint: String by memoize { "${targetClassId.shortClassName}MembersInjector" }

    /**
     * Returns the [Parameter] for the given [typeKey], or null if not found. This is used to trace
     * which injected member (property/function) requires a specific dependency.
     */
    fun parameterFor(typeKey: IrTypeKey): Parameter? =
      parameters.nonDispatchParameters.find { it.typeKey == typeKey }

    override fun renderDescriptionDiagnostic(short: Boolean, underlineTypeKey: Boolean) =
      buildString {
        typeKey.qualifier?.let {
          append(it.render(short = short))
          append(' ')
        }
        append("MembersInjector<")
        append(targetClassId.shortClassName.asString())
        append('>')
        if (function != null) {
          appendLine()
          appendLine("(injected at)")
          append("  ")
          renderForDiagnostic(
            declaration = function,
            short = short,
            typeKey = typeKey,
            annotations = MetroAnnotations.none(),
            parameters = parameters,
            isProperty = function.isPropertyAccessor,
            underlineTypeKey = underlineTypeKey,
            format = Format.CALL,
          )
        }
      }

    override fun toString() = renderDescriptionDiagnostic(short = true, underlineTypeKey = false)
  }

  /**
   * Represents a graph extension binding. Graph extensions are treated as bindings to enable
   * standard code generation.
   *
   * Note: GraphExtension bindings are specially handled in [BindingPropertyCollector] to only ever
   * be getter properties if used by child graphs or reused.
   */
  @Poko
  class GraphExtension(
    override val typeKey: IrTypeKey,
    @Poko.Skip val parent: IrClass,
    val accessor: IrSimpleFunction,
    parentGraphKey: IrTypeKey,
  ) : IrBinding {
    override val dependencies: List<IrContextualTypeKey> =
      listOf(IrContextualTypeKey(parentGraphKey))
    override val reportableDeclaration: IrDeclarationWithName = accessor
    override val contextualTypeKey: IrContextualTypeKey = IrContextualTypeKey(typeKey)
    override val parameters: Parameters = Parameters.empty()
    override val isImplicitlyDeferrable: Boolean = true

    // The scope field always returns null for GraphExtension
    // Use shouldBeScoped to check if this binding needs to be scoped
    override val scope: IrAnnotation? = null

    override val nameHint: String = typeKey.type.rawType().name.asString()

    override fun renderDescriptionDiagnostic(short: Boolean, underlineTypeKey: Boolean) =
      buildString {
        renderForDiagnostic(
          declaration = accessor,
          annotations = MetroAnnotations.none(),
          short = short,
          typeKey = typeKey,
          underlineTypeKey = underlineTypeKey,
          parameters = Parameters.empty(),
          isProperty = accessor.isPropertyAccessor,
        )
      }

    override fun toString() = renderDescriptionDiagnostic(short = true, underlineTypeKey = false)
  }

  /**
   * Represents a graph extension factory binding. These are factories that create graph extensions
   * and need to participate in the binding graph for proper dependency resolution.
   */
  @Poko
  class GraphExtensionFactory(
    override val typeKey: IrTypeKey,
    val extensionTypeKey: IrTypeKey,
    val parent: IrClass,
    parentKey: IrTypeKey,
    val accessor: IrSimpleFunction,
  ) : IrBinding {
    override val dependencies: List<IrContextualTypeKey> = listOf(IrContextualTypeKey(parentKey))
    override val reportableDeclaration: IrDeclarationWithName = accessor
    override val contextualTypeKey: IrContextualTypeKey = IrContextualTypeKey(typeKey)
    override val parameters: Parameters = Parameters.empty()
    override val scope: IrAnnotation? = null
    override val nameHint: String = "${typeKey.type.rawType().name.asString()}Factory"

    override fun renderDescriptionDiagnostic(short: Boolean, underlineTypeKey: Boolean) =
      buildString {
        renderForDiagnostic(
          declaration = accessor,
          annotations = MetroAnnotations.none(),
          short = short,
          typeKey = typeKey,
          underlineTypeKey = underlineTypeKey,
          parameters = Parameters.empty(),
          isProperty = accessor.isPropertyAccessor,
        )
      }

    override fun toString() = renderDescriptionDiagnostic(short = true, underlineTypeKey = false)
  }

  /**
   * A custom wrapping type, such as an [java.util.Optional].
   *
   * Some types may natively support absence. To indicate this, set [wrappedContextKey] to indicate
   * [hasDefault = true][IrContextualTypeKey.hasDefault].
   *
   * Wrapper types may not have scopes.
   */
  @Poko
  class CustomWrapper(
    override val typeKey: IrTypeKey,
    val wrappedType: IrType,
    val wrappedContextKey: IrContextualTypeKey,
    // TODO
    //  could have multiple, do we want to report?
    //  this is the mirror function in local decls
    @Poko.Skip val declaration: IrSimpleFunction,
    val allowsAbsent: Boolean,
    val wrapperKey: String,
  ) : IrBinding {
    override val dependencies: List<IrContextualTypeKey> = listOf(wrappedContextKey)
    override val reportableDeclaration: IrDeclarationWithName = declaration
    override val contextualTypeKey: IrContextualTypeKey = IrContextualTypeKey(typeKey)
    override val parameters: Parameters = Parameters.empty()
    override val scope: IrAnnotation? = null
    override val nameHint: String = "$wrapperKey${wrappedType.rawType().name.asString()}"

    override fun renderDescriptionDiagnostic(short: Boolean, underlineTypeKey: Boolean) =
      buildString {
        renderForDiagnostic(
          declaration = declaration,
          annotations = MetroAnnotations.none(),
          short = short,
          typeKey = typeKey,
          underlineTypeKey = underlineTypeKey,
          parameters = Parameters.empty(),
          isProperty = declaration.isPropertyAccessor,
        )
      }

    override fun toString() = renderDescriptionDiagnostic(short = true, underlineTypeKey = false)
  }
}

internal val IrBinding.isIntoMultibinding: Boolean
  get() {
    return typeKey.qualifier?.ir?.annotationClass?.classId == Symbols.ClassIds.MultibindingElement
  }

internal val IrBinding.hostParent: IrDeclarationContainer?
  get() {
    return when (val decl = reportableDeclaration) {
      is IrClass -> decl
      is IrPackageFragment -> decl
      is IrFunction,
      is IrProperty ->
        decl.parentDeclarationsWithSelf.firstNotNullOfOrNull {
          it as? IrClass ?: it as? IrPackageFragment
        }
      else -> null
    }
  }
